name: Setup Node
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        node-version-file: .node-version
        cache: pnpm
    - run: npx corepack enable
      shell: bash
    - run: pnpm i
      shell: bash
