name: Setup Node
inputs:
  build:
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm
    - run: npm run corepack
      shell: bash
    - run: pnpm i
      shell: bash
    - run: pnpm build
      if: inputs.build == 'true'
      shell: bash
