services:
  vrt:
    build:
      context: .
      dockerfile: vrt.dockerfile
    image: hiroppy-site-vrt:latest
    env_file:
      - ./.env
    volumes:
      - ./test-results:/app/test-results
      - ./tests:/app/tests
    network_mode: "host"
    stdin_open: true
    tty: true
