onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - hiroppy
  - lefthook
  - msw
  - puppeteer
  - sharp
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - hiroppy
allowBuilds:
  hiroppy: true
  lefthook: true
  msw: true
  sharp: true
