onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - hiroppy
  - lefthook
  - msw
  - puppeteer
  - sharp
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - hiroppy
  # Renovate security update: next@16.1.7
  - next@16.1.7
  # Renovate security update: postcss@8.5.10
  - postcss@8.5.10
